# Generated by Django 4.2.7 on 2023-11-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='Email: ')),
            ],
        ),
        migrations.CreateModel(
            name='Notegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medical_study_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Notecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medical_study_app.client')),
                ('notegroup', models.ManyToManyField(blank=True, null=True, to='medical_study_app.notegroup')),
            ],
        ),
    ]
