# Generated by Django 4.2.7 on 2023-11-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_study_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecard',
            name='notegroup',
            field=models.ManyToManyField(blank=True, to='medical_study_app.notegroup'),
        ),
    ]
