# Generated by Django 4.2.7 on 2023-11-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_study_app', '0002_alter_notecard_notegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notegroup',
            name='about',
        ),
    ]
